### ISSUE TITLE
Introduce a BOM

### ISSUE THREAD

**Issue by gastaldi** [metawidget/metawidget#48]
It would be nice to have a BOM with all the modules so it can be included in my parent pom.xml's dependencyManagement using the `<scope>imported</scope>` and declare the modules in every subproject without the need to specify the version.

**Comment by kennardconsulting** [comment]
Hello again George!

I would love to do this. However I'm not clear how it works?

As I understand it, a BOM is like dependency management for when the modules don't implicitly include themselves. So for example if you include metawidget-faces.jar it will automatically drag in metawidget-core.jar (using standard Maven dependency). However if you wanted to include all of Metawidget's sibling JARs (say, metawidget-faces and metawidget-spring) a BOM could be useful.

However we already have metawidget-all.jar for that purpose?

Could you explain what you would be using the BOM for, so that I can get it right?

**Comment by gastaldi** [comment]
Here is an example on how it works: https://github.com/arquillian/arquillian-universe-bom

Basically you define all modules in a pom.xml and you can import that pom in your project so you don´t need to specify the modules version when adding a dependency to each of them (this is not useful if you use metawidget-all)

**Comment by kennardconsulting** [comment]
Thanks for helping me through this!

So I already have a pom.xml defined here for metawidget-all.jar: https://github.com/metawidget/metawidget/blob/master/modules/java/all/pom.xml

I assume this is close to what we need? Some questions:

1. Am I allowed to use ${project.version} in a BOM pom.xml?
2. Do I need to include those few dependencies that are otherwise implied (for example, I haven't explicitly included metawidget-core)
3. Should I place the BOM pom.xml in modules/java/bom as a new project, or in the root of modules/java? If that latter, it will be alongside an existing pom.xml, which may be confusing?

**Comment by gastaldi** [comment]
1. Yes, but I guess the packaging needs to be POM
2. Yes, if there are cases where metawidget-core is the only dependency needed
3. I think it makes sense to have a modules/java/bom in this case.

**Comment by kennardconsulting** [comment]
Okay can you please review https://github.com/metawidget/metawidget/blob/master/modules/java/bom/pom.xml for me?

**Comment by gastaldi** [comment]
Looks great! Good job
